# docker-compose.yaml
version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: blinkit-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - blinkit-network

  user-service:
    build: ./backend/user-service
    container_name: blinkit-user-service
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - JWT_SECRET=blinkit-secret-key-2024
    depends_on:
      - mongodb
    networks:
      - blinkit-network

  product-service:
    build: ./backend/product-service
    container_name: blinkit-product-service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - blinkit-network

  cart-order-service:
    build: ./backend/cart-order-service
    container_name: blinkit-cart-order-service
    ports:
      - "8003:8003"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - JWT_SECRET=blinkit-secret-key-2024
      - DELIVERY_SERVICE_URL=http://delivery-service:8004
      - PRODUCT_SERVICE_URL=http://product-service:8002
    depends_on:
      - mongodb
      - delivery-service
      - product-service
    networks:
      - blinkit-network

  delivery-service:
    build: ./backend/delivery-service
    container_name: blinkit-delivery-service
    ports:
      - "8004:8004"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - blinkit-network

  api-gateway:
    build: ./backend/api-gateway
    container_name: blinkit-api-gateway
    ports:
      - "8000:8000"
    environment:
      - USER_SERVICE_URL=http://user-service:8001
      - PRODUCT_SERVICE_URL=http://product-service:8002
      - CART_ORDER_SERVICE_URL=http://cart-order-service:8003
      - DELIVERY_SERVICE_URL=http://delivery-service:8004
    depends_on:
      - user-service
      - product-service
      - cart-order-service
      - delivery-service
    networks:
      - blinkit-network

volumes:
  mongodb_data:

networks:
  blinkit-network:
    driver: bridge