# k8s/delivery-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: blinkit-delivery-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8004
          env:
            - name: MONGO_URL
              value: "mongodb://mongodb:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
    - port: 8004
      targetPort: 8004
  type: ClusterIP